name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Check project
        run: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Project contents:"
          ls -la "Omni core v1"

      - name: Make Gradle executable
        working-directory: "Omni core v1"
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: "Omni core v1"
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Omni-core-debug
          path: "Omni core v1/app/build/outputs/apk/debug/*.apk"
